INSERT INTO users (username, password, admin) VALUES
  ('happyelephant104', 'looking', false),
  ('silverlion883', 'blueball', false),
  ('blackcat538', 'call', false),
  ('lazypanda833', 'kristy', false),
  ('bluesnake996', 'tattoo', false),
  ('bluetiger647', 'sebring', false),
  ('angryladybug472', 'oldone', false),
  ('whitemouse199', '353535', false),
  ('sadfrog156', 'crave', false),
  ('angryladybug543', 'colonel', false),
  ('katlyn', 'foxes_are_cute', true),
  ('crazysnake303', 'break', false),
  ('blackrabbit385', 'smile', false),
  ('crazyfrog417', 'duane', false),
  ('greenmouse609', 'gators1', false),
  ('notadmin', 'hewwo', true),
  ('yellowpeacock629', 'tickling', false),
  ('tinylion929', 'woody', false),
  ('sadmeercat513', 'anders', false),
  ('ticklishkoala870', 'frog', false),
  ('whitekoala299', 'nine', false),
  ('brownelephant473', 'asimov', false),
  ('angryfish391', 'rockon', false),
  ('purplepeacock643', 'edison', false),
  ('sadpeacock413', 'browns', false),
  ('silvermeercat675', 'bulls', false),
  ('orangemouse552', '12345678', false),
  ('lazyladybug919', 'greece', false),
  ('happyfrog920', 'penny', false),
  ('lazyduck695', 'dirty1', false),
  ('orangemouse994', 'morrison', false),
  ('crazybird521', 'sheridan', false),
  ('lazywolf999', 'garrett', false),
  ('yellowrabbit830', 'brittany', false),
  ('angrypanda973', 'berger', false),
  ('blueduck967', 'blackcat', false),
  ('tinyleopard794', 'vernon', false),
  ('coolfox35', '5up3r53cur3', false);

INSERT INTO foxes (url, description, likes) VALUES
('https://this-is-a-l.ink/with/foxes/16/0004.gif', 'red fox resting beneath a tree''s branches', 0),
('https://this-is-a-l.ink/with/foxes/16/0006.gif', 'smiling over the fence', 0),
('https://this-is-a-l.ink/with/foxes/16/0008.gif', 'red fox gazing in to the distance', 0),
('https://this-is-a-l.ink/with/foxes/16/0010.gif', 'fennek foxes large ears help them listen for food', 0),
('https://this-is-a-l.ink/with/foxes/16/0011.gif', 'red fox stretching out its legs', 0),
('https://this-is-a-l.ink/with/foxes/16/0012.gif', 'fennek fox posing for the camera', 0),
('https://this-is-a-l.ink/with/foxes/16/0013.gif', 'sleepy fox laying in the flowers', 0),
('https://this-is-a-l.ink/with/foxes/16/0015.gif', 'fennek foxes always look tired', 0),
('https://this-is-a-l.ink/with/foxes/16/0016.gif', 'using its telepathi powers to convince you that foxes are cute', 0),
('https://this-is-a-l.ink/with/foxes/16/0018.gif', 'fox loaves in training', 0),
('https://this-is-a-l.ink/with/foxes/16/0019.gif', 'foxes love getting that itch scratched just right', 0),
('https://this-is-a-l.ink/with/foxes/16/0020.gif', 'fennek foxes are the best at stacking', 0),
('https://this-is-a-l.ink/with/foxes/16/0021.gif', 'fox tails make comfy pillows', 0),
('https://this-is-a-l.ink/with/foxes/16/0022.gif', 'a thick coat of fur keeps them warm', 0),
('https://this-is-a-l.ink/with/foxes/16/0023.gif', 'fennek fox attempting to look angry (it doesn''t work)', 0),
('https://this-is-a-l.ink/with/foxes/16/0024.gif', 'smelling the cameraman', 0),
('https://this-is-a-l.ink/with/foxes/16/0025.gif', 'it''s not often a fox gets a ride in someone''s arms', 0),
('https://this-is-a-l.ink/with/foxes/16/0026.gif', 'playing in the snow is fun for foxes of all ages', 0),
('https://this-is-a-l.ink/with/foxes/16/0027.gif', 'leaves aren''t the most nutritious, but they crunch like nothing else', 0),
('https://this-is-a-l.ink/with/foxes/16/0028.gif', 'the progression of loaf', 0),
('https://this-is-a-l.ink/with/foxes/16/0029.gif', 'fennek stalking the cameraman', 0),
('https://this-is-a-l.ink/with/foxes/16/0030.gif', 'the smallest foxes can fit in your hands', 0),
('https://this-is-a-l.ink/with/foxes/16/0031.gif', 'a fox being krauled under its chin', 0),
('https://this-is-a-l.ink/with/foxes/16/0032.gif', 'baby fox snuggled in the covers', 0),
('https://this-is-a-l.ink/with/foxes/16/0033.gif', 'aaaaaaaaaaaaaa', 0),
('https://this-is-a-l.ink/with/foxes/16/0034.gif', 'i wonder what they''re looking at', 0),
('https://this-is-a-l.ink/with/foxes/16/0035.gif', 'this fox looks like its fallen in love O.O', 0),
('https://this-is-a-l.ink/with/foxes/16/0036.gif', 'baby fox kit being taken care of', 0),
('https://this-is-a-l.ink/with/foxes/16/0038.gif', 'young fox kit peeking out from its mother''s tail', 0),
('https://this-is-a-l.ink/with/foxes/16/0039.gif', 'fox kit loaf', 0),
('https://this-is-a-l.ink/with/foxes/16/0040.gif', 'note to reader: foxes cannot get a drivers license', 0),
('https://this-is-a-l.ink/with/foxes/16/0041.gif', 'small fennek resting its paws on a human hand', 0),
('https://this-is-a-l.ink/with/foxes/16/0042.gif', 'fennek fox peeking out of its den', 0),
('https://this-is-a-l.ink/with/foxes/16/0043.gif', 'two fennek foxes playing together', 0),
('https://this-is-a-l.ink/with/foxes/16/0044.gif', 'fox being happy about a hug', 0),
('https://this-is-a-l.ink/with/foxes/16/0045.gif', 'fennek doin a blep', 0),
('https://this-is-a-l.ink/with/foxes/16/0047.gif', 'fennek on high alert', 0),
('https://this-is-a-l.ink/with/foxes/16/0014.gif', 'cutie fox with a collar', 1),
('https://this-is-a-l.ink/with/foxes/16/0001.gif', 'a fox lounging on a couch', 1),
('https://this-is-a-l.ink/with/foxes/16/0017.gif', 'remember to stop and smell the flowers', 1),
('https://this-is-a-l.ink/with/foxes/16/0046.gif', 'tired fennek about to snooze', 1),
('https://this-is-a-l.ink/with/foxes/16/0002.gif', 'two fox kits playing on the grass', 12),
('https://this-is-a-l.ink/with/foxes/16/0005.gif', 'a friendly fox giving advice', 1),
('https://this-is-a-l.ink/with/foxes/16/0037.gif', 'monch the stawberry mmmmmm', 4),
('https://this-is-a-l.ink/with/foxes/16/0009.gif', 'problem fox doesn''t mind the attention', 2),
('https://this-is-a-l.ink/with/foxes/16/0003.gif', 'fennek foxes falling in love', 1),
('https://this-is-a-l.ink/with/foxes/16/0007.gif', 'sleepy fennek showing off their paws', 2);
